[versions]
androidGradlePlugin = "8.3.1"
kotlin = "1.9.23"
gradleVersionsPlugin = "0.51.0"
kotlinxCoroutines = "1.8.0"

androidxCore = "1.12.0"
androidxAppCompat = "1.6.1"
androidxBrowser = "1.8.0"
androidxLifecycle = "2.7.0"
androidxPreferences = "1.2.1"
material = "1.11.0"
playCore = "1.10.3"
playCoreKtx = "1.8.1"

# debug
leakcanary = "2.13"
flipper = "0.250.0"
soloader = "0.11.0"

ktlint = "1.2.1"

# for release

[libraries]
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

androidxCore = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidxAppCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidxBrowser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidxLifecycleProcess = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidxLifecycleViewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidxPreferences = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreferences" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
playCore = { group = "com.google.android.play", name = "core", version.ref = "playCore" }
playCoreKtx = { group = "com.google.android.play", name = "core-ktx", version.ref = "playCoreKtx" }

# debug
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
flipper = { group = "com.facebook.flipper", name = "flipper", version.ref = "flipper" }
soloader = { group = "com.facebook.soloader", name = "soloader", version.ref = "soloader" }
flipperNetwork = { group = "com.facebook.flipper", name = "flipper-network-plugin", version.ref = "flipper" }
flipperLeakCanary2 = { group = "com.facebook.flipper", name = "flipper-leakcanary2-plugin", version.ref = "flipper" }

ktlint = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

# for release

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }

# for release

[bundles]
flipper = [
    "flipper",
    "soloader",
    "flipperNetwork",
    "flipperLeakCanary2"
]

# for release
