[versions]
androidGradlePlugin = "9.3.1"
desugarJdkLibs = "2.1.5"
kotlin = "2.4.10"
ksp = "2.3.10"
hilt = "2.60.1"
kotlinxCoroutines = "1.11.0"
dependencyGuard = "0.5.0"
versionCatalogUpdate = "1.1.0"

androidxCore = "1.19.0"
androidxAppCompat = "1.7.1"
androidxBrowser = "1.10.0"
androidxLifecycle = "2.11.0"
androidxPreferences = "1.2.1"
androidxDataStore = "1.2.1"
androidxActivity = "1.13.0"
androidxHiltCompose = "1.4.0"
composeBom = "2026.06.01"
material = "1.14.0"
playAppUpdate = "2.1.0"

ktlint = "1.8.0"

# for release

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }

kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

androidxCore = { group = "androidx.core", name = "core", version.ref = "androidxCore" }
androidxAppCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidxBrowser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidxLifecycleProcess = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidxLifecycleViewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidxLifecycle" }
androidxLifecycleViewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidxLifecycleRuntimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidxPreferences = { group = "androidx.preference", name = "preference", version.ref = "androidxPreferences" }
androidxDataStorePreferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidxHiltCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltCompose" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidxComposeUi = { group = "androidx.compose.ui", name = "ui" }
androidxComposeUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidxComposeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidxComposeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
androidxComposeMaterialIcons = { group = "androidx.compose.material", name = "material-icons-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
playAppUpdate = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "playAppUpdate" }

hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hiltAndroidCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

ktlint = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

# for release

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }

# for release

[bundles]

# for release
